[project]
name = "resin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.4.3",
    "duckdb-engine>=0.17.0",
    "ipykernel>=7.1.0",
    "sqlalchemy>=2.0.45",
    "sqlparse>=0.5.4",
]
